# Development environment values for Acme SampleApp Backend
# Overrides values.yaml for the dev deployment

backend:
  replicaCount: 1

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

cloudSql:
  proxy:
    image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
