resource "local_file" "pet" {
  filename = var.fileName   # Ensure the directory is writable

  #Id is the attribute of the resource of my_pet
  content  = "Here is the Random Pet ${random_pet.my_pet.id}"

  depends_on = [
    random_pet.my_pet
  ]
}

resource "random_pet" "my_pet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.name_length
}

output "pet_output" {
  description = "Record the value of pet ID generated by the random_pet resource"
  value = random_pet.my_pet.id
}